// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.mattermost.mscalendar",
    "name": "Microsoft Calendar",
    "description": "Microsoft Calendar Integration",
    "homepage_url": "https://mattermost.com/pl/mattermost-plugin-mscalendar",
    "support_url": "https://github.com/mattermost/mattermost-plugin-mscalendar/issues",
    "release_notes_url": "https://mattermost.com/pl/mattermost-plugin-mscalendar/releases/tag/v1.6.0",
    "icon_path": "assets/profile-mscalendar.svg",
    "version": "1.6.0+d305959",
    "min_server_version": "10.7.0",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "darwin-arm64": "server/dist/plugin-darwin-arm64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "linux-arm64": "server/dist/plugin-linux-arm64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": [
            {
                "key": "AdminUserIDs",
                "display_name": "Admin User IDs:",
                "type": "text",
                "help_text": "List of users authorized to administer the plugin in addition to the System Admins. Must be a comma-separated list of user IDs.\\n \\n User IDs can be found in **System Console \u003e User Management \u003e Users**. Select the user's name, and the ID is displayed in the top-right corner of the banner.",
                "placeholder": "",
                "default": null,
                "hosting": "",
                "secret": false
            },
            {
                "key": "AdminLogLevel",
                "display_name": "Copy plugin logs to admins, as bot messages:",
                "type": "dropdown",
                "help_text": "Select the log level.",
                "placeholder": "",
                "default": "none",
                "options": [
                    {
                        "display_name": "None",
                        "value": "none"
                    },
                    {
                        "display_name": "Debug",
                        "value": "debug"
                    },
                    {
                        "display_name": "Info",
                        "value": "info"
                    },
                    {
                        "display_name": "Warning",
                        "value": "warn"
                    },
                    {
                        "display_name": "Error",
                        "value": "error"
                    }
                ],
                "hosting": "",
                "secret": false
            },
            {
                "key": "AdminLogVerbose",
                "display_name": "Display full context for each admin log message:",
                "type": "bool",
                "help_text": "",
                "placeholder": "",
                "default": false,
                "hosting": "",
                "secret": false
            },
            {
                "key": "EnableExperimentalUI",
                "display_name": "Enable Experimental Calendar UI:",
                "type": "bool",
                "help_text": "When true, a calendar sidebar and channel header button are registered in the Mattermost UI. This feature is experimental and may change in future releases.",
                "placeholder": "",
                "default": false,
                "hosting": "",
                "secret": false
            },
            {
                "key": "ForceOAuth2Consent",
                "display_name": "Force OAuth2 Consent Prompt:",
                "type": "bool",
                "help_text": "When true, users are always prompted to grant consent during the OAuth2 connect flow. Disable this if your Azure AD tenant policy restricts user consent and you have already granted admin consent for the application.",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            },
            {
                "key": "OAuth2Authority",
                "display_name": "Azure Directory (tenant) ID:",
                "type": "text",
                "help_text": "Directory (tenant) ID.",
                "placeholder": "",
                "default": null,
                "hosting": "",
                "secret": false
            },
            {
                "key": "OAuth2ClientId",
                "display_name": "Azure Application (client) ID:",
                "type": "text",
                "help_text": "Microsoft Office Client ID.",
                "placeholder": "",
                "default": "",
                "hosting": "",
                "secret": false
            },
            {
                "key": "OAuth2ClientSecret",
                "display_name": "Microsoft Office Client Secret:",
                "type": "text",
                "help_text": "Microsoft Office Client Secret.",
                "placeholder": "",
                "default": "",
                "hosting": "",
                "secret": true
            },
            {
                "key": "OAuth2ForceConsent",
                "display_name": "Force OAuth2 consent prompt:",
                "type": "bool",
                "help_text": "When true, users are always prompted for consent during OAuth2 authorization. Set to false if your Azure/Entra configuration requires admin consent for registered applications and non-admin users are encountering authorization errors.",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            }
        ],
        "sections": null
    }
}
`);

export default manifest;
