// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mattermost/mattermost-plugin-msoffice/server/store (interfaces: OAuth2StateStore)

// Package mock_store is a generated GoMock package.
package mock_store

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockOAuth2StateStore is a mock of OAuth2StateStore interface
type MockOAuth2StateStore struct {
	ctrl     *gomock.Controller
	recorder *MockOAuth2StateStoreMockRecorder
}

// MockOAuth2StateStoreMockRecorder is the mock recorder for MockOAuth2StateStore
type MockOAuth2StateStoreMockRecorder struct {
	mock *MockOAuth2StateStore
}

// NewMockOAuth2StateStore creates a new mock instance
func NewMockOAuth2StateStore(ctrl *gomock.Controller) *MockOAuth2StateStore {
	mock := &MockOAuth2StateStore{ctrl: ctrl}
	mock.recorder = &MockOAuth2StateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOAuth2StateStore) EXPECT() *MockOAuth2StateStoreMockRecorder {
	return m.recorder
}

// StoreOAuth2State mocks base method
func (m *MockOAuth2StateStore) StoreOAuth2State(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreOAuth2State", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreOAuth2State indicates an expected call of StoreOAuth2State
func (mr *MockOAuth2StateStoreMockRecorder) StoreOAuth2State(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreOAuth2State", reflect.TypeOf((*MockOAuth2StateStore)(nil).StoreOAuth2State), arg0)
}

// VerifyOAuth2State mocks base method
func (m *MockOAuth2StateStore) VerifyOAuth2State(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyOAuth2State", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyOAuth2State indicates an expected call of VerifyOAuth2State
func (mr *MockOAuth2StateStoreMockRecorder) VerifyOAuth2State(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyOAuth2State", reflect.TypeOf((*MockOAuth2StateStore)(nil).VerifyOAuth2State), arg0)
}
