// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mattermost/mattermost-plugin-mscalendar/calendar/engine (interfaces: Engine)

// Package mock_engine is a generated GoMock package.
package mock_engine

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	engine "github.com/mattermost/mattermost-plugin-mscalendar/calendar/engine"
	remote "github.com/mattermost/mattermost-plugin-mscalendar/calendar/remote"
	store "github.com/mattermost/mattermost-plugin-mscalendar/calendar/store"
)

// MockEngine is a mock of Engine interface.
type MockEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEngineMockRecorder
}

// MockEngineMockRecorder is the mock recorder for MockEngine.
type MockEngineMockRecorder struct {
	mock *MockEngine
}

// NewMockEngine creates a new mock instance.
func NewMockEngine(ctrl *gomock.Controller) *MockEngine {
	mock := &MockEngine{ctrl: ctrl}
	mock.recorder = &MockEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngine) EXPECT() *MockEngineMockRecorder {
	return m.recorder
}

// AcceptEvent mocks base method.
func (m *MockEngine) AcceptEvent(arg0 *engine.User, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptEvent indicates an expected call of AcceptEvent.
func (mr *MockEngineMockRecorder) AcceptEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptEvent", reflect.TypeOf((*MockEngine)(nil).AcceptEvent), arg0, arg1)
}

// AfterDisconnect mocks base method.
func (m *MockEngine) AfterDisconnect(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterDisconnect", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AfterDisconnect indicates an expected call of AfterDisconnect.
func (mr *MockEngineMockRecorder) AfterDisconnect(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterDisconnect", reflect.TypeOf((*MockEngine)(nil).AfterDisconnect), arg0)
}

// AfterSuccessfullyConnect mocks base method.
func (m *MockEngine) AfterSuccessfullyConnect(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterSuccessfullyConnect", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AfterSuccessfullyConnect indicates an expected call of AfterSuccessfullyConnect.
func (mr *MockEngineMockRecorder) AfterSuccessfullyConnect(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterSuccessfullyConnect", reflect.TypeOf((*MockEngine)(nil).AfterSuccessfullyConnect), arg0, arg1)
}

// ClearSettingsPosts mocks base method.
func (m *MockEngine) ClearSettingsPosts(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearSettingsPosts", arg0)
}

// ClearSettingsPosts indicates an expected call of ClearSettingsPosts.
func (mr *MockEngineMockRecorder) ClearSettingsPosts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSettingsPosts", reflect.TypeOf((*MockEngine)(nil).ClearSettingsPosts), arg0)
}

// CreateCalendar mocks base method.
func (m *MockEngine) CreateCalendar(arg0 *engine.User, arg1 *remote.Calendar) (*remote.Calendar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCalendar", arg0, arg1)
	ret0, _ := ret[0].(*remote.Calendar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCalendar indicates an expected call of CreateCalendar.
func (mr *MockEngineMockRecorder) CreateCalendar(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCalendar", reflect.TypeOf((*MockEngine)(nil).CreateCalendar), arg0, arg1)
}

// CreateEvent mocks base method.
func (m *MockEngine) CreateEvent(arg0 *engine.User, arg1 *remote.Event, arg2 []string) (*remote.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", arg0, arg1, arg2)
	ret0, _ := ret[0].(*remote.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockEngineMockRecorder) CreateEvent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockEngine)(nil).CreateEvent), arg0, arg1, arg2)
}

// CreateMyEventSubscription mocks base method.
func (m *MockEngine) CreateMyEventSubscription() (*store.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMyEventSubscription")
	ret0, _ := ret[0].(*store.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMyEventSubscription indicates an expected call of CreateMyEventSubscription.
func (mr *MockEngineMockRecorder) CreateMyEventSubscription() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMyEventSubscription", reflect.TypeOf((*MockEngine)(nil).CreateMyEventSubscription))
}

// DeclineEvent mocks base method.
func (m *MockEngine) DeclineEvent(arg0 *engine.User, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeclineEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeclineEvent indicates an expected call of DeclineEvent.
func (mr *MockEngineMockRecorder) DeclineEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeclineEvent", reflect.TypeOf((*MockEngine)(nil).DeclineEvent), arg0, arg1)
}

// DeleteCalendar mocks base method.
func (m *MockEngine) DeleteCalendar(arg0 *engine.User, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCalendar", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCalendar indicates an expected call of DeleteCalendar.
func (mr *MockEngineMockRecorder) DeleteCalendar(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCalendar", reflect.TypeOf((*MockEngine)(nil).DeleteCalendar), arg0, arg1)
}

// DeleteMyEventSubscription mocks base method.
func (m *MockEngine) DeleteMyEventSubscription() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMyEventSubscription")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMyEventSubscription indicates an expected call of DeleteMyEventSubscription.
func (mr *MockEngineMockRecorder) DeleteMyEventSubscription() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMyEventSubscription", reflect.TypeOf((*MockEngine)(nil).DeleteMyEventSubscription))
}

// DeleteOrphanedSubscription mocks base method.
func (m *MockEngine) DeleteOrphanedSubscription(arg0 *store.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrphanedSubscription", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrphanedSubscription indicates an expected call of DeleteOrphanedSubscription.
func (mr *MockEngineMockRecorder) DeleteOrphanedSubscription(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrphanedSubscription", reflect.TypeOf((*MockEngine)(nil).DeleteOrphanedSubscription), arg0)
}

// DisconnectUser mocks base method.
func (m *MockEngine) DisconnectUser(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisconnectUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisconnectUser indicates an expected call of DisconnectUser.
func (mr *MockEngineMockRecorder) DisconnectUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisconnectUser", reflect.TypeOf((*MockEngine)(nil).DisconnectUser), arg0)
}

// FindMeetingTimes mocks base method.
func (m *MockEngine) FindMeetingTimes(arg0 *engine.User, arg1 *remote.FindMeetingTimesParameters) (*remote.MeetingTimeSuggestionResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMeetingTimes", arg0, arg1)
	ret0, _ := ret[0].(*remote.MeetingTimeSuggestionResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMeetingTimes indicates an expected call of FindMeetingTimes.
func (mr *MockEngineMockRecorder) FindMeetingTimes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMeetingTimes", reflect.TypeOf((*MockEngine)(nil).FindMeetingTimes), arg0, arg1)
}

// GetActingUser mocks base method.
func (m *MockEngine) GetActingUser() *engine.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActingUser")
	ret0, _ := ret[0].(*engine.User)
	return ret0
}

// GetActingUser indicates an expected call of GetActingUser.
func (mr *MockEngineMockRecorder) GetActingUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActingUser", reflect.TypeOf((*MockEngine)(nil).GetActingUser))
}

// GetCalendarViews mocks base method.
func (m *MockEngine) GetCalendarViews(arg0 []*store.User) ([]*remote.ViewCalendarResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCalendarViews", arg0)
	ret0, _ := ret[0].([]*remote.ViewCalendarResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCalendarViews indicates an expected call of GetCalendarViews.
func (mr *MockEngineMockRecorder) GetCalendarViews(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCalendarViews", reflect.TypeOf((*MockEngine)(nil).GetCalendarViews), arg0)
}

// GetCalendars mocks base method.
func (m *MockEngine) GetCalendars(arg0 *engine.User) ([]*remote.Calendar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCalendars", arg0)
	ret0, _ := ret[0].([]*remote.Calendar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCalendars indicates an expected call of GetCalendars.
func (mr *MockEngineMockRecorder) GetCalendars(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCalendars", reflect.TypeOf((*MockEngine)(nil).GetCalendars), arg0)
}

// GetDailySummarySettingsForUser mocks base method.
func (m *MockEngine) GetDailySummarySettingsForUser(arg0 *engine.User) (*store.DailySummaryUserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailySummarySettingsForUser", arg0)
	ret0, _ := ret[0].(*store.DailySummaryUserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailySummarySettingsForUser indicates an expected call of GetDailySummarySettingsForUser.
func (mr *MockEngineMockRecorder) GetDailySummarySettingsForUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailySummarySettingsForUser", reflect.TypeOf((*MockEngine)(nil).GetDailySummarySettingsForUser), arg0)
}

// GetDaySummaryForUser mocks base method.
func (m *MockEngine) GetDaySummaryForUser(arg0 time.Time, arg1 *engine.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDaySummaryForUser", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDaySummaryForUser indicates an expected call of GetDaySummaryForUser.
func (mr *MockEngineMockRecorder) GetDaySummaryForUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDaySummaryForUser", reflect.TypeOf((*MockEngine)(nil).GetDaySummaryForUser), arg0, arg1)
}

// GetRemoteUser mocks base method.
func (m *MockEngine) GetRemoteUser(arg0 string) (*remote.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteUser", arg0)
	ret0, _ := ret[0].(*remote.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemoteUser indicates an expected call of GetRemoteUser.
func (mr *MockEngineMockRecorder) GetRemoteUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteUser", reflect.TypeOf((*MockEngine)(nil).GetRemoteUser), arg0)
}

// GetTimezone mocks base method.
func (m *MockEngine) GetTimezone(arg0 *engine.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimezone", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimezone indicates an expected call of GetTimezone.
func (mr *MockEngineMockRecorder) GetTimezone(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimezone", reflect.TypeOf((*MockEngine)(nil).GetTimezone), arg0)
}

// GetUserSettings mocks base method.
func (m *MockEngine) GetUserSettings(arg0 *engine.User) (*store.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSettings", arg0)
	ret0, _ := ret[0].(*store.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSettings indicates an expected call of GetUserSettings.
func (mr *MockEngineMockRecorder) GetUserSettings(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSettings", reflect.TypeOf((*MockEngine)(nil).GetUserSettings), arg0)
}

// IsAuthorizedAdmin mocks base method.
func (m *MockEngine) IsAuthorizedAdmin(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorizedAdmin", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAuthorizedAdmin indicates an expected call of IsAuthorizedAdmin.
func (mr *MockEngineMockRecorder) IsAuthorizedAdmin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorizedAdmin", reflect.TypeOf((*MockEngine)(nil).IsAuthorizedAdmin), arg0)
}

// ListRemoteSubscriptions mocks base method.
func (m *MockEngine) ListRemoteSubscriptions() ([]*remote.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRemoteSubscriptions")
	ret0, _ := ret[0].([]*remote.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRemoteSubscriptions indicates an expected call of ListRemoteSubscriptions.
func (mr *MockEngineMockRecorder) ListRemoteSubscriptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRemoteSubscriptions", reflect.TypeOf((*MockEngine)(nil).ListRemoteSubscriptions))
}

// LoadMyEventSubscription mocks base method.
func (m *MockEngine) LoadMyEventSubscription() (*store.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadMyEventSubscription")
	ret0, _ := ret[0].(*store.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadMyEventSubscription indicates an expected call of LoadMyEventSubscription.
func (mr *MockEngineMockRecorder) LoadMyEventSubscription() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadMyEventSubscription", reflect.TypeOf((*MockEngine)(nil).LoadMyEventSubscription))
}

// PrintSettings mocks base method.
func (m *MockEngine) PrintSettings(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintSettings", arg0)
}

// PrintSettings indicates an expected call of PrintSettings.
func (mr *MockEngineMockRecorder) PrintSettings(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintSettings", reflect.TypeOf((*MockEngine)(nil).PrintSettings), arg0)
}

// ProcessAllDailySummary mocks base method.
func (m *MockEngine) ProcessAllDailySummary(arg0 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessAllDailySummary", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessAllDailySummary indicates an expected call of ProcessAllDailySummary.
func (mr *MockEngineMockRecorder) ProcessAllDailySummary(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessAllDailySummary", reflect.TypeOf((*MockEngine)(nil).ProcessAllDailySummary), arg0)
}

// RenewMyEventSubscription mocks base method.
func (m *MockEngine) RenewMyEventSubscription() (*store.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenewMyEventSubscription")
	ret0, _ := ret[0].(*store.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenewMyEventSubscription indicates an expected call of RenewMyEventSubscription.
func (mr *MockEngineMockRecorder) RenewMyEventSubscription() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewMyEventSubscription", reflect.TypeOf((*MockEngine)(nil).RenewMyEventSubscription))
}

// RespondToEvent mocks base method.
func (m *MockEngine) RespondToEvent(arg0 *engine.User, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RespondToEvent", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RespondToEvent indicates an expected call of RespondToEvent.
func (mr *MockEngineMockRecorder) RespondToEvent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondToEvent", reflect.TypeOf((*MockEngine)(nil).RespondToEvent), arg0, arg1, arg2)
}

// SetDailySummaryEnabled mocks base method.
func (m *MockEngine) SetDailySummaryEnabled(arg0 *engine.User, arg1 bool) (*store.DailySummaryUserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDailySummaryEnabled", arg0, arg1)
	ret0, _ := ret[0].(*store.DailySummaryUserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDailySummaryEnabled indicates an expected call of SetDailySummaryEnabled.
func (mr *MockEngineMockRecorder) SetDailySummaryEnabled(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDailySummaryEnabled", reflect.TypeOf((*MockEngine)(nil).SetDailySummaryEnabled), arg0, arg1)
}

// SetDailySummaryPostTime mocks base method.
func (m *MockEngine) SetDailySummaryPostTime(arg0 *engine.User, arg1 string) (*store.DailySummaryUserSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDailySummaryPostTime", arg0, arg1)
	ret0, _ := ret[0].(*store.DailySummaryUserSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDailySummaryPostTime indicates an expected call of SetDailySummaryPostTime.
func (mr *MockEngineMockRecorder) SetDailySummaryPostTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDailySummaryPostTime", reflect.TypeOf((*MockEngine)(nil).SetDailySummaryPostTime), arg0, arg1)
}

// Sync mocks base method.
func (m *MockEngine) Sync(arg0 string) (string, *engine.StatusSyncJobSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*engine.StatusSyncJobSummary)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Sync indicates an expected call of Sync.
func (mr *MockEngineMockRecorder) Sync(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockEngine)(nil).Sync), arg0)
}

// SyncAll mocks base method.
func (m *MockEngine) SyncAll() (string, *engine.StatusSyncJobSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncAll")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*engine.StatusSyncJobSummary)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SyncAll indicates an expected call of SyncAll.
func (mr *MockEngineMockRecorder) SyncAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncAll", reflect.TypeOf((*MockEngine)(nil).SyncAll))
}

// TentativelyAcceptEvent mocks base method.
func (m *MockEngine) TentativelyAcceptEvent(arg0 *engine.User, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TentativelyAcceptEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// TentativelyAcceptEvent indicates an expected call of TentativelyAcceptEvent.
func (mr *MockEngineMockRecorder) TentativelyAcceptEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TentativelyAcceptEvent", reflect.TypeOf((*MockEngine)(nil).TentativelyAcceptEvent), arg0, arg1)
}

// ViewCalendar mocks base method.
func (m *MockEngine) ViewCalendar(arg0 *engine.User, arg1, arg2 time.Time) ([]*remote.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewCalendar", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*remote.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewCalendar indicates an expected call of ViewCalendar.
func (mr *MockEngineMockRecorder) ViewCalendar(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewCalendar", reflect.TypeOf((*MockEngine)(nil).ViewCalendar), arg0, arg1, arg2)
}

// Welcome mocks base method.
func (m *MockEngine) Welcome(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Welcome", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Welcome indicates an expected call of Welcome.
func (mr *MockEngineMockRecorder) Welcome(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Welcome", reflect.TypeOf((*MockEngine)(nil).Welcome), arg0)
}

// WelcomeFlowEnd mocks base method.
func (m *MockEngine) WelcomeFlowEnd(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WelcomeFlowEnd", arg0)
}

// WelcomeFlowEnd indicates an expected call of WelcomeFlowEnd.
func (mr *MockEngineMockRecorder) WelcomeFlowEnd(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WelcomeFlowEnd", reflect.TypeOf((*MockEngine)(nil).WelcomeFlowEnd), arg0)
}
