// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mattermost/mattermost-plugin-mscalendar/server/api (interfaces: Client)

// Package mock_api is a generated GoMock package.
package mock_api

import (
	gomock "github.com/golang/mock/gomock"
	remote "github.com/mattermost/mattermost-plugin-mscalendar/server/remote"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// MakeClient mocks base method
func (m *MockClient) MakeClient() (remote.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeClient")
	ret0, _ := ret[0].(remote.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeClient indicates an expected call of MakeClient
func (mr *MockClientMockRecorder) MakeClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeClient", reflect.TypeOf((*MockClient)(nil).MakeClient))
}

// MakeSuperuserClient mocks base method
func (m *MockClient) MakeSuperuserClient() (remote.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeSuperuserClient")
	ret0, _ := ret[0].(remote.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeSuperuserClient indicates an expected call of MakeSuperuserClient
func (mr *MockClientMockRecorder) MakeSuperuserClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeSuperuserClient", reflect.TypeOf((*MockClient)(nil).MakeSuperuserClient))
}
