// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mattermost/mattermost-plugin-msoffice/server/utils (interfaces: BotPoster)

// Package mock_utils is a generated GoMock package.
package mock_utils

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBotPoster is a mock of BotPoster interface
type MockBotPoster struct {
	ctrl     *gomock.Controller
	recorder *MockBotPosterMockRecorder
}

// MockBotPosterMockRecorder is the mock recorder for MockBotPoster
type MockBotPosterMockRecorder struct {
	mock *MockBotPoster
}

// NewMockBotPoster creates a new mock instance
func NewMockBotPoster(ctrl *gomock.Controller) *MockBotPoster {
	mock := &MockBotPoster{ctrl: ctrl}
	mock.recorder = &MockBotPosterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBotPoster) EXPECT() *MockBotPosterMockRecorder {
	return m.recorder
}

// PostDirect mocks base method
func (m *MockBotPoster) PostDirect(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostDirect", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostDirect indicates an expected call of PostDirect
func (mr *MockBotPosterMockRecorder) PostDirect(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostDirect", reflect.TypeOf((*MockBotPoster)(nil).PostDirect), arg0, arg1, arg2)
}

// PostEphemeral mocks base method
func (m *MockBotPoster) PostEphemeral(arg0, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PostEphemeral", arg0, arg1, arg2)
}

// PostEphemeral indicates an expected call of PostEphemeral
func (mr *MockBotPosterMockRecorder) PostEphemeral(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostEphemeral", reflect.TypeOf((*MockBotPoster)(nil).PostEphemeral), arg0, arg1, arg2)
}
