package utils

var windowsToIanaMap = map[string]string{}

func ConvertWindowsTimezoneToIANA(winTZ string) string {
	if len(windowsToIanaMap) == 0 {
		populateConversionMap()
	}

	tz, ok := windowsToIanaMap[winTZ]
	if ok {
		return tz
	}

	return ""
}

func populateConversionMap() {
	for _, entry := range allTimezones {
		windowsToIanaMap[entry[1]] = entry[0]
	}
}

// Format: {IANA, Windows, offset}
// Source: https://techsupport.osisoft.com/Documentation/PI-Web-API/help/topics/timezones/iana.html
var allTimezones = [][]string{
	{"Africa/Abidjan", "Greenwich Standard Time", "+00:00"},
	{"Africa/Accra", "Greenwich Standard Time", "+00:00"},
	{"Africa/Addis_Ababa", "E. Africa Standard Time", "+03:00"},
	{"Africa/Algiers", "W. Central Africa Standard Time", "+01:00"},
	{"Africa/Asmara", "E. Africa Standard Time", "+03:00"},
	{"Africa/Asmera", "E. Africa Standard Time", "+03:00"},
	{"Africa/Bamako", "Greenwich Standard Time", "+00:00"},
	{"Africa/Bangui", "W. Central Africa Standard Time", "+01:00"},
	{"Africa/Banjul", "Greenwich Standard Time", "+00:00"},
	{"Africa/Bissau", "Greenwich Standard Time", "+00:00"},
	{"Africa/Blantyre", "South Africa Standard Time", "+02:00"},
	{"Africa/Brazzaville", "W. Central Africa Standard Time", "+01:00"},
	{"Africa/Bujumbura", "South Africa Standard Time", "+02:00"},
	{"Africa/Cairo", "Egypt Standard Time", "+02:00"},
	{"Africa/Casablanca", "Morocco Standard Time", "+00:00"},
	{"Africa/Ceuta", "Romance Standard Time", "+01:00"},
	{"Africa/Conakry", "Greenwich Standard Time", "+00:00"},
	{"Africa/Dakar", "Greenwich Standard Time", "+00:00"},
	{"Africa/Dar_es_Salaam", "E. Africa Standard Time", "+03:00"},
	{"Africa/Djibouti", "E. Africa Standard Time", "+03:00"},
	{"Africa/Douala", "W. Central Africa Standard Time", "+01:00"},
	{"Africa/El_Aaiun", "Morocco Standard Time", "+00:00"},
	{"Africa/Freetown", "Greenwich Standard Time", "+00:00"},
	{"Africa/Gaborone", "South Africa Standard Time", "+02:00"},
	{"Africa/Harare", "South Africa Standard Time", "+02:00"},
	{"Africa/Johannesburg", "South Africa Standard Time", "+02:00"},
	{"Africa/Juba", "E. Africa Standard Time", "+03:00"},
	{"Africa/Kampala", "E. Africa Standard Time", "+03:00"},
	{"Africa/Khartoum", "E. Africa Standard Time", "+03:00"},
	{"Africa/Kigali", "South Africa Standard Time", "+02:00"},
	{"Africa/Kinshasa", "W. Central Africa Standard Time", "+01:00"},
	{"Africa/Lagos", "W. Central Africa Standard Time", "+01:00"},
	{"Africa/Libreville", "W. Central Africa Standard Time", "+01:00"},
	{"Africa/Lome", "Greenwich Standard Time", "+00:00"},
	{"Africa/Luanda", "W. Central Africa Standard Time", "+01:00"},
	{"Africa/Lubumbashi", "South Africa Standard Time", "+02:00"},
	{"Africa/Lusaka", "South Africa Standard Time", "+02:00"},
	{"Africa/Malabo", "W. Central Africa Standard Time", "+01:00"},
	{"Africa/Maputo", "South Africa Standard Time", "+02:00"},
	{"Africa/Maseru", "South Africa Standard Time", "+02:00"},
	{"Africa/Mbabane", "South Africa Standard Time", "+02:00"},
	{"Africa/Mogadishu", "E. Africa Standard Time", "+03:00"},
	{"Africa/Monrovia", "Greenwich Standard Time", "+00:00"},
	{"Africa/Nairobi", "E. Africa Standard Time", "+03:00"},
	{"Africa/Ndjamena", "W. Central Africa Standard Time", "+01:00"},
	{"Africa/Niamey", "W. Central Africa Standard Time", "+01:00"},
	{"Africa/Nouakchott", "Greenwich Standard Time", "+00:00"},
	{"Africa/Ouagadougou", "Greenwich Standard Time", "+00:00"},
	{"Africa/Porto-Novo", "W. Central Africa Standard Time", "+01:00"},
	{"Africa/Sao_Tome", "Greenwich Standard Time", "+00:00"},
	{"Africa/Timbuktu", "Greenwich Standard Time", "+00:00"},
	{"Africa/Tripoli", "Libya Standard Time", "+02:00"},
	{"Africa/Tunis", "W. Central Africa Standard Time", "+01:00"},
	{"Africa/Windhoek", "Namibia Standard Time", "+02:00"},
	{"America/Adak", "Aleutian Standard Time", "-10:00"},
	{"America/Anchorage", "Alaskan Standard Time", "-09:00"},
	{"America/Anguilla", "SA Western Standard Time", "-04:00"},
	{"America/Antigua", "SA Western Standard Time", "-04:00"},
	{"America/Araguaina", "Tocantins Standard Time", "-03:00"},
	{"America/Argentina/Buenos_Aires", "Argentina Standard Time", "-03:00"},
	{"America/Argentina/Catamarca", "Argentina Standard Time", "-03:00"},
	{"America/Argentina/ComodRivadavia", "Argentina Standard Time", "-03:00"},
	{"America/Argentina/Cordoba", "Argentina Standard Time", "-03:00"},
	{"America/Argentina/Jujuy", "Argentina Standard Time", "-03:00"},
	{"America/Argentina/La_Rioja", "Argentina Standard Time", "-03:00"},
	{"America/Argentina/Mendoza", "Argentina Standard Time", "-03:00"},
	{"America/Argentina/Rio_Gallegos", "Argentina Standard Time", "-03:00"},
	{"America/Argentina/Salta", "Argentina Standard Time", "-03:00"},
	{"America/Argentina/San_Juan", "Argentina Standard Time", "-03:00"},
	{"America/Argentina/San_Luis", "Argentina Standard Time", "-03:00"},
	{"America/Argentina/Tucuman", "Argentina Standard Time", "-03:00"},
	{"America/Argentina/Ushuaia", "Argentina Standard Time", "-03:00"},
	{"America/Aruba", "SA Western Standard Time", "-04:00"},
	{"America/Asuncion", "Paraguay Standard Time", "-04:00"},
	{"America/Atikokan", "SA Pacific Standard Time", "-05:00"},
	{"America/Atka", "Aleutian Standard Time", "-10:00"},
	{"America/Bahia", "Bahia Standard Time", "-03:00"},
	{"America/Bahia_Banderas", "Central Standard Time (Mexico)", "-06:00"},
	{"America/Barbados", "SA Western Standard Time", "-04:00"},
	{"America/Belem", "SA Eastern Standard Time", "-03:00"},
	{"America/Belize", "Central America Standard Time", "-06:00"},
	{"America/Blanc-Sablon", "SA Western Standard Time", "-04:00"},
	{"America/Boa_Vista", "SA Western Standard Time", "-04:00"},
	{"America/Bogota", "SA Pacific Standard Time", "-05:00"},
	{"America/Boise", "Mountain Standard Time", "-07:00"},
	{"America/Buenos_Aires", "Argentina Standard Time", "-03:00"},
	{"America/Cambridge_Bay", "Mountain Standard Time", "-07:00"},
	{"America/Campo_Grande", "Central Brazilian Standard Time", "-04:00"},
	{"America/Cancun", "Eastern Standard Time (Mexico)", "-05:00"},
	{"America/Caracas", "Venezuela Standard Time", "-04:00"},
	{"America/Catamarca", "Argentina Standard Time", "-03:00"},
	{"America/Cayenne", "SA Eastern Standard Time", "-03:00"},
	{"America/Cayman", "SA Pacific Standard Time", "-05:00"},
	{"America/Chicago", "Central Standard Time", "-06:00"},
	{"America/Chihuahua", "Mountain Standard Time (Mexico)", "-07:00"},
	{"America/Coral_Harbour", "SA Pacific Standard Time", "-05:00"},
	{"America/Cordoba", "Argentina Standard Time", "-03:00"},
	{"America/Costa_Rica", "Central America Standard Time", "-06:00"},
	{"America/Creston", "US Mountain Standard Time", "-07:00"},
	{"America/Cuiaba", "Central Brazilian Standard Time", "-04:00"},
	{"America/Curacao", "SA Western Standard Time", "-04:00"},
	{"America/Danmarkshavn", "UTC", "+00:00"},
	{"America/Dawson", "Pacific Standard Time", "-08:00"},
	{"America/Dawson_Creek", "US Mountain Standard Time", "-07:00"},
	{"America/Denver", "Mountain Standard Time", "-07:00"},
	{"America/Detroit", "Eastern Standard Time", "-05:00"},
	{"America/Dominica", "SA Western Standard Time", "-04:00"},
	{"America/Edmonton", "Mountain Standard Time", "-07:00"},
	{"America/Eirunepe", "SA Pacific Standard Time", "-05:00"},
	{"America/El_Salvador", "Central America Standard Time", "-06:00"},
	{"America/Ensenada", "Pacific Standard Time (Mexico)", "-08:00"},
	{"America/Fortaleza", "SA Eastern Standard Time", "-03:00"},
	{"America/Fort_Nelson", "US Mountain Standard Time", "-07:00"},
	{"America/Fort_Wayne", "US Eastern Standard Time", "-05:00"},
	{"America/Glace_Bay", "Atlantic Standard Time", "-04:00"},
	{"America/Godthab", "Greenland Standard Time", "-03:00"},
	{"America/Goose_Bay", "Atlantic Standard Time", "-04:00"},
	{"America/Grand_Turk", "Turks And Caicos Standard Time", "-05:00"},
	{"America/Grenada", "SA Western Standard Time", "-04:00"},
	{"America/Guadeloupe", "SA Western Standard Time", "-04:00"},
	{"America/Guatemala", "Central America Standard Time", "-06:00"},
	{"America/Guayaquil", "SA Pacific Standard Time", "-05:00"},
	{"America/Guyana", "SA Western Standard Time", "-04:00"},
	{"America/Halifax", "Atlantic Standard Time", "-04:00"},
	{"America/Havana", "Cuba Standard Time", "-05:00"},
	{"America/Hermosillo", "US Mountain Standard Time", "-07:00"},
	{"America/Indiana/Indianapolis", "US Eastern Standard Time", "-05:00"},
	{"America/Indiana/Knox", "Central Standard Time", "-06:00"},
	{"America/Indiana/Marengo", "US Eastern Standard Time", "-05:00"},
	{"America/Indiana/Petersburg", "Eastern Standard Time", "-05:00"},
	{"America/Indiana/Tell_City", "Central Standard Time", "-06:00"},
	{"America/Indiana/Vevay", "US Eastern Standard Time", "-05:00"},
	{"America/Indiana/Vincennes", "Eastern Standard Time", "-05:00"},
	{"America/Indiana/Winamac", "Eastern Standard Time", "-05:00"},
	{"America/Indianapolis", "US Eastern Standard Time", "-05:00"},
	{"America/Inuvik", "Mountain Standard Time", "-07:00"},
	{"America/Iqaluit", "Eastern Standard Time", "-05:00"},
	{"America/Jamaica", "SA Pacific Standard Time", "-05:00"},
	{"America/Jujuy", "Argentina Standard Time", "-03:00"},
	{"America/Juneau", "Alaskan Standard Time", "-09:00"},
	{"America/Kentucky/Louisville", "Eastern Standard Time", "-05:00"},
	{"America/Kentucky/Monticello", "Eastern Standard Time", "-05:00"},
	{"America/Knox_IN", "Central Standard Time", "-06:00"},
	{"America/Kralendijk", "SA Western Standard Time", "-04:00"},
	{"America/La_Paz", "SA Western Standard Time", "-04:00"},
	{"America/Lima", "SA Pacific Standard Time", "-05:00"},
	{"America/Los_Angeles", "Pacific Standard Time", "-08:00"},
	{"America/Louisville", "Eastern Standard Time", "-05:00"},
	{"America/Lower_Princes", "SA Western Standard Time", "-04:00"},
	{"America/Maceio", "SA Eastern Standard Time", "-03:00"},
	{"America/Managua", "Central America Standard Time", "-06:00"},
	{"America/Manaus", "SA Western Standard Time", "-04:00"},
	{"America/Marigot", "SA Western Standard Time", "-04:00"},
	{"America/Martinique", "SA Western Standard Time", "-04:00"},
	{"America/Matamoros", "Central Standard Time", "-06:00"},
	{"America/Mazatlan", "Mountain Standard Time (Mexico)", "-07:00"},
	{"America/Mendoza", "Argentina Standard Time", "-03:00"},
	{"America/Menominee", "Central Standard Time", "-06:00"},
	{"America/Merida", "Central Standard Time (Mexico)", "-06:00"},
	{"America/Metlakatla", "Alaskan Standard Time", "-09:00"},
	{"America/Mexico_City", "Central Standard Time (Mexico)", "-06:00"},
	{"America/Miquelon", "Saint Pierre Standard Time", "-03:00"},
	{"America/Moncton", "Atlantic Standard Time", "-04:00"},
	{"America/Monterrey", "Central Standard Time (Mexico)", "-06:00"},
	{"America/Montevideo", "Montevideo Standard Time", "-03:00"},
	{"America/Montreal", "Eastern Standard Time", "-05:00"},
	{"America/Montserrat", "SA Western Standard Time", "-04:00"},
	{"America/Nassau", "Eastern Standard Time", "-05:00"},
	{"America/New_York", "Eastern Standard Time", "-05:00"},
	{"America/Nipigon", "Eastern Standard Time", "-05:00"},
	{"America/Nome", "Alaskan Standard Time", "-09:00"},
	{"America/Noronha", "UTC-02", "-02:00"},
	{"America/North_Dakota/Beulah", "Central Standard Time", "-06:00"},
	{"America/North_Dakota/Center", "Central Standard Time", "-06:00"},
	{"America/North_Dakota/New_Salem", "Central Standard Time", "-06:00"},
	{"America/Ojinaga", "Mountain Standard Time", "-07:00"},
	{"America/Panama", "SA Pacific Standard Time", "-05:00"},
	{"America/Pangnirtung", "Eastern Standard Time", "-05:00"},
	{"America/Paramaribo", "SA Eastern Standard Time", "-03:00"},
	{"America/Phoenix", "US Mountain Standard Time", "-07:00"},
	{"America/Port-au-Prince", "Haiti Standard Time", "-05:00"},
	{"America/Porto_Acre", "SA Pacific Standard Time", "-05:00"},
	{"America/Porto_Velho", "SA Western Standard Time", "-04:00"},
	{"America/Port_of_Spain", "SA Western Standard Time", "-04:00"},
	{"America/Puerto_Rico", "SA Western Standard Time", "-04:00"},
	{"America/Rainy_River", "Central Standard Time", "-06:00"},
	{"America/Rankin_Inlet", "Central Standard Time", "-06:00"},
	{"America/Recife", "SA Eastern Standard Time", "-03:00"},
	{"America/Regina", "Canada Central Standard Time", "-06:00"},
	{"America/Resolute", "Central Standard Time", "-06:00"},
	{"America/Rio_Branco", "SA Pacific Standard Time", "-05:00"},
	{"America/Rosario", "Argentina Standard Time", "-03:00"},
	{"America/Santarem", "SA Eastern Standard Time", "-03:00"},
	{"America/Santa_Isabel", "Pacific Standard Time (Mexico)", "-08:00"},
	{"America/Santiago", "Pacific SA Standard Time", "-04:00"},
	{"America/Santo_Domingo", "SA Western Standard Time", "-04:00"},
	{"America/Sao_Paulo", "E. South America Standard Time", "-03:00"},
	{"America/Scoresbysund", "Azores Standard Time", "-01:00"},
	{"America/Shiprock", "Mountain Standard Time", "-07:00"},
	{"America/Sitka", "Alaskan Standard Time", "-09:00"},
	{"America/St_Barthelemy", "SA Western Standard Time", "-04:00"},
	{"America/St_Johns", "Newfoundland Standard Time", "-03:30"},
	{"America/St_Kitts", "SA Western Standard Time", "-04:00"},
	{"America/St_Lucia", "SA Western Standard Time", "-04:00"},
	{"America/St_Thomas", "SA Western Standard Time", "-04:00"},
	{"America/St_Vincent", "SA Western Standard Time", "-04:00"},
	{"America/Swift_Current", "Canada Central Standard Time", "-06:00"},
	{"America/Tegucigalpa", "Central America Standard Time", "-06:00"},
	{"America/Thule", "Atlantic Standard Time", "-04:00"},
	{"America/Thunder_Bay", "Eastern Standard Time", "-05:00"},
	{"America/Tijuana", "Pacific Standard Time (Mexico)", "-08:00"},
	{"America/Toronto", "Eastern Standard Time", "-05:00"},
	{"America/Tortola", "SA Western Standard Time", "-04:00"},
	{"America/Vancouver", "Pacific Standard Time", "-08:00"},
	{"America/Virgin", "SA Western Standard Time", "-04:00"},
	{"America/Whitehorse", "Pacific Standard Time", "-08:00"},
	{"America/Winnipeg", "Central Standard Time", "-06:00"},
	{"America/Yakutat", "Alaskan Standard Time", "-09:00"},
	{"America/Yellowknife", "Mountain Standard Time", "-07:00"},
	{"Antarctica/Casey", "W. Australia Standard Time", "+08:00"},
	{"Antarctica/Davis", "SE Asia Standard Time", "+07:00"},
	{"Antarctica/DumontDUrville", "West Pacific Standard Time", "+10:00"},
	{"Antarctica/Macquarie", "Central Pacific Standard Time", "+11:00"},
	{"Antarctica/Mawson", "West Asia Standard Time", "+05:00"},
	{"Antarctica/McMurdo", "New Zealand Standard Time", "+12:00"},
	{"Antarctica/Palmer", "Pacific SA Standard Time", "-04:00"},
	{"Antarctica/Rothera", "SA Eastern Standard Time", "-03:00"},
	{"Antarctica/South_Pole", "New Zealand Standard Time", "+12:00"},
	{"Antarctica/Syowa", "E. Africa Standard Time", "+03:00"},
	{"Antarctica/Vostok", "Central Asia Standard Time", "+06:00"},
	{"Arctic/Longyearbyen", "W. Europe Standard Time", "+01:00"},
	{"Asia/Aden", "Arab Standard Time", "+03:00"},
	{"Asia/Almaty", "Central Asia Standard Time", "+06:00"},
	{"Asia/Amman", "Jordan Standard Time", "+02:00"},
	{"Asia/Anadyr", "Russia Time Zone 11", "+12:00"},
	{"Asia/Aqtau", "West Asia Standard Time", "+05:00"},
	{"Asia/Aqtobe", "West Asia Standard Time", "+05:00"},
	{"Asia/Ashgabat", "West Asia Standard Time", "+05:00"},
	{"Asia/Ashkhabad", "West Asia Standard Time", "+05:00"},
	{"Asia/Baghdad", "Arabic Standard Time", "+03:00"},
	{"Asia/Bahrain", "Arab Standard Time", "+03:00"},
	{"Asia/Baku", "Azerbaijan Standard Time", "+04:00"},
	{"Asia/Bangkok", "SE Asia Standard Time", "+07:00"},
	{"Asia/Barnaul", "Altai Standard Time", "+07:00"},
	{"Asia/Beirut", "Middle East Standard Time", "+02:00"},
	{"Asia/Bishkek", "Central Asia Standard Time", "+06:00"},
	{"Asia/Brunei", "Singapore Standard Time", "+08:00"},
	{"Asia/Calcutta", "India Standard Time", "+05:30"},
	{"Asia/Chita", "Transbaikal Standard Time", "+09:00"},
	{"Asia/Choibalsan", "Ulaanbaatar Standard Time", "+08:00"},
	{"Asia/Chongqing", "China Standard Time", "+08:00"},
	{"Asia/Chungking", "China Standard Time", "+08:00"},
	{"Asia/Colombo", "Sri Lanka Standard Time", "+05:30"},
	{"Asia/Dacca", "Bangladesh Standard Time", "+06:00"},
	{"Asia/Damascus", "Syria Standard Time", "+02:00"},
	{"Asia/Dhaka", "Bangladesh Standard Time", "+06:00"},
	{"Asia/Dili", "Tokyo Standard Time", "+09:00"},
	{"Asia/Dubai", "Arabian Standard Time", "+04:00"},
	{"Asia/Dushanbe", "West Asia Standard Time", "+05:00"},
	{"Asia/Gaza", "West Bank Standard Time", "+02:00"},
	{"Asia/Harbin", "China Standard Time", "+08:00"},
	{"Asia/Hebron", "West Bank Standard Time", "+02:00"},
	{"Asia/Hong_Kong", "China Standard Time", "+08:00"},
	{"Asia/Hovd", "W. Mongolia Standard Time", "+07:00"},
	{"Asia/Ho_Chi_Minh", "SE Asia Standard Time", "+07:00"},
	{"Asia/Irkutsk", "North Asia East Standard Time", "+08:00"},
	{"Asia/Istanbul", "Turkey Standard Time", "+03:00"},
	{"Asia/Jakarta", "SE Asia Standard Time", "+07:00"},
	{"Asia/Jayapura", "Tokyo Standard Time", "+09:00"},
	{"Asia/Jerusalem", "Israel Standard Time", "+02:00"},
	{"Asia/Kabul", "Afghanistan Standard Time", "+04:30"},
	{"Asia/Kamchatka", "Russia Time Zone 11", "+12:00"},
	{"Asia/Karachi", "Pakistan Standard Time", "+05:00"},
	{"Asia/Kashgar", "Central Asia Standard Time", "+06:00"},
	{"Asia/Kathmandu", "Nepal Standard Time", "+05:45"},
	{"Asia/Katmandu", "Nepal Standard Time", "+05:45"},
	{"Asia/Khandyga", "Yakutsk Standard Time", "+09:00"},
	{"Asia/Kolkata", "India Standard Time", "+05:30"},
	{"Asia/Krasnoyarsk", "North Asia Standard Time", "+07:00"},
	{"Asia/Kuala_Lumpur", "Singapore Standard Time", "+08:00"},
	{"Asia/Kuching", "Singapore Standard Time", "+08:00"},
	{"Asia/Kuwait", "Arab Standard Time", "+03:00"},
	{"Asia/Macao", "China Standard Time", "+08:00"},
	{"Asia/Macau", "China Standard Time", "+08:00"},
	{"Asia/Magadan", "Magadan Standard Time", "+11:00"},
	{"Asia/Makassar", "Singapore Standard Time", "+08:00"},
	{"Asia/Manila", "Singapore Standard Time", "+08:00"},
	{"Asia/Muscat", "Arabian Standard Time", "+04:00"},
	{"Asia/Nicosia", "GTB Standard Time", "+02:00"},
	{"Asia/Novokuznetsk", "North Asia Standard Time", "+07:00"},
	{"Asia/Novosibirsk", "N. Central Asia Standard Time", "+07:00"},
	{"Asia/Omsk", "N. Central Asia Standard Time", "+07:00"},
	{"Asia/Oral", "West Asia Standard Time", "+05:00"},
	{"Asia/Phnom_Penh", "SE Asia Standard Time", "+07:00"},
	{"Asia/Pontianak", "SE Asia Standard Time", "+07:00"},
	{"Asia/Pyongyang", "North Korea Standard Time", "+09:00"},
	{"Asia/Qatar", "Arab Standard Time", "+03:00"},
	{"Asia/Qyzylorda", "Central Asia Standard Time", "+06:00"},
	{"Asia/Rangoon", "Myanmar Standard Time", "+06:30"},
	{"Asia/Riyadh", "Arab Standard Time", "+03:00"},
	{"Asia/Saigon", "SE Asia Standard Time", "+07:00"},
	{"Asia/Sakhalin", "Sakhalin Standard Time", "+11:00"},
	{"Asia/Samarkand", "West Asia Standard Time", "+05:00"},
	{"Asia/Seoul", "Korea Standard Time", "+09:00"},
	{"Asia/Shanghai", "China Standard Time", "+08:00"},
	{"Asia/Singapore", "Singapore Standard Time", "+08:00"},
	{"Asia/Srednekolymsk", "Russia Time Zone 10", "+11:00"},
	{"Asia/Taipei", "Taipei Standard Time", "+08:00"},
	{"Asia/Tashkent", "West Asia Standard Time", "+05:00"},
	{"Asia/Tbilisi", "Georgian Standard Time", "+04:00"},
	{"Asia/Tehran", "Iran Standard Time", "+03:30"},
	{"Asia/Tel_Aviv", "Israel Standard Time", "+02:00"},
	{"Asia/Thimbu", "Bangladesh Standard Time", "+06:00"},
	{"Asia/Thimphu", "Bangladesh Standard Time", "+06:00"},
	{"Asia/Tokyo", "Tokyo Standard Time", "+09:00"},
	{"Asia/Tomsk", "Tomsk Standard Time", "+07:00"},
	{"Asia/Ujung_Pandang", "Singapore Standard Time", "+08:00"},
	{"Asia/Ulaanbaatar", "Ulaanbaatar Standard Time", "+08:00"},
	{"Asia/Ulan_Bator", "Ulaanbaatar Standard Time", "+08:00"},
	{"Asia/Urumqi", "Central Asia Standard Time", "+06:00"},
	{"Asia/Ust-Nera", "Vladivostok Standard Time", "+10:00"},
	{"Asia/Vientiane", "SE Asia Standard Time", "+07:00"},
	{"Asia/Vladivostok", "Vladivostok Standard Time", "+10:00"},
	{"Asia/Yakutsk", "Yakutsk Standard Time", "+09:00"},
	{"Asia/Yekaterinburg", "Ekaterinburg Standard Time", "+05:00"},
	{"Asia/Yerevan", "Caucasus Standard Time", "+04:00"},
	{"Atlantic/Azores", "Azores Standard Time", "-01:00"},
	{"Atlantic/Bermuda", "Atlantic Standard Time", "-04:00"},
	{"Atlantic/Canary", "GMT Standard Time", "+00:00"},
	{"Atlantic/Cape_Verde", "Cape Verde Standard Time", "-01:00"},
	{"Atlantic/Faeroe", "GMT Standard Time", "+00:00"},
	{"Atlantic/Faroe", "GMT Standard Time", "+00:00"},
	{"Atlantic/Jan_Mayen", "W. Europe Standard Time", "+01:00"},
	{"Atlantic/Madeira", "GMT Standard Time", "+00:00"},
	{"Atlantic/Reykjavik", "Greenwich Standard Time", "+00:00"},
	{"Atlantic/South_Georgia", "UTC-02", "-02:00"},
	{"Atlantic/Stanley", "SA Eastern Standard Time", "-03:00"},
	{"Atlantic/St_Helena", "Greenwich Standard Time", "+00:00"},
	{"Australia/ACT", "AUS Eastern Standard Time", "+10:00"},
	{"Australia/Adelaide", "Cen. Australia Standard Time", "+09:30"},
	{"Australia/Brisbane", "E. Australia Standard Time", "+10:00"},
	{"Australia/Broken_Hill", "Cen. Australia Standard Time", "+09:30"},
	{"Australia/Canberra", "AUS Eastern Standard Time", "+10:00"},
	{"Australia/Currie", "Tasmania Standard Time", "+10:00"},
	{"Australia/Darwin", "AUS Central Standard Time", "+09:30"},
	{"Australia/Eucla", "Aus Central W. Standard Time", "+08:45"},
	{"Australia/Hobart", "Tasmania Standard Time", "+10:00"},
	{"Australia/LHI", "Lord Howe Standard Time", "+10:30"},
	{"Australia/Lindeman", "E. Australia Standard Time", "+10:00"},
	{"Australia/Lord_Howe", "Lord Howe Standard Time", "+10:30"},
	{"Australia/Melbourne", "AUS Eastern Standard Time", "+10:00"},
	{"Australia/North", "AUS Central Standard Time", "+09:30"},
	{"Australia/NSW", "AUS Eastern Standard Time", "+10:00"},
	{"Australia/Perth", "W. Australia Standard Time", "+08:00"},
	{"Australia/Queensland", "E. Australia Standard Time", "+10:00"},
	{"Australia/South", "Cen. Australia Standard Time", "+09:30"},
	{"Australia/Sydney", "AUS Eastern Standard Time", "+10:00"},
	{"Australia/Tasmania", "Tasmania Standard Time", "+10:00"},
	{"Australia/Victoria", "AUS Eastern Standard Time", "+10:00"},
	{"Australia/West", "W. Australia Standard Time", "+08:00"},
	{"Australia/Yancowinna", "Cen. Australia Standard Time", "+09:30"},
	{"Brazil/Acre", "SA Pacific Standard Time", "-05:00"},
	{"Brazil/DeNoronha", "UTC-02", "-02:00"},
	{"Brazil/East", "E. South America Standard Time", "-03:00"},
	{"Brazil/West", "SA Western Standard Time", "-04:00"},
	{"Canada/Atlantic", "Atlantic Standard Time", "-04:00"},
	{"Canada/Central", "Central Standard Time", "-06:00"},
	{"Canada/East-Saskatchewan", "Canada Central Standard Time", "-06:00"},
	{"Canada/Eastern", "Eastern Standard Time", "-05:00"},
	{"Canada/Mountain", "Mountain Standard Time", "-07:00"},
	{"Canada/Newfoundland", "Newfoundland Standard Time", "-03:30"},
	{"Canada/Pacific", "Pacific Standard Time", "-08:00"},
	{"Canada/Saskatchewan", "Canada Central Standard Time", "-06:00"},
	{"Canada/Yukon", "Pacific Standard Time", "-08:00"},
	{"Chile/Continental", "Pacific SA Standard Time", "-04:00"},
	{"Chile/EasterIsland", "Easter Island Standard Time", "-06:00"},
	{"CST6CDT", "Central Standard Time", "-06:00"},
	{"Cuba", "Cuba Standard Time", "-05:00"},
	{"Egypt", "Egypt Standard Time", "+02:00"},
	{"Eire", "GMT Standard Time", "+00:00"},
	{"EST", "SA Pacific Standard Time", "-05:00"},
	{"EST5EDT", "Eastern Standard Time", "-05:00"},
	{"Etc/GMT", "UTC", "+00:00"},
	{"Etc/GMT+0", "UTC", "+00:00"},
	{"Etc/GMT+1", "Cape Verde Standard Time", "-01:00"},
	{"Etc/GMT+10", "Hawaiian Standard Time", "-10:00"},
	{"Etc/GMT+11", "UTC-11", "-11:00"},
	{"Etc/GMT+12", "Dateline Standard Time", "-12:00"},
	{"Etc/GMT+2", "UTC-02", "-02:00"},
	{"Etc/GMT+3", "SA Eastern Standard Time", "-03:00"},
	{"Etc/GMT+4", "SA Western Standard Time", "-04:00"},
	{"Etc/GMT+5", "SA Pacific Standard Time", "-05:00"},
	{"Etc/GMT+6", "Central America Standard Time", "-06:00"},
	{"Etc/GMT+7", "US Mountain Standard Time", "-07:00"},
	{"Etc/GMT+8", "UTC-08", "-08:00"},
	{"Etc/GMT+9", "UTC-09", "-09:00"},
	{"Etc/GMT-0", "UTC", "+00:00"},
	{"Etc/GMT-1", "W. Central Africa Standard Time", "+01:00"},
	{"Etc/GMT-10", "West Pacific Standard Time", "+10:00"},
	{"Etc/GMT-11", "Central Pacific Standard Time", "+11:00"},
	{"Etc/GMT-12", "UTC+12", "+12:00"},
	{"Etc/GMT-13", "Tonga Standard Time", "+13:00"},
	{"Etc/GMT-14", "Line Islands Standard Time", "+14:00"},
	{"Etc/GMT-2", "South Africa Standard Time", "+02:00"},
	{"Etc/GMT-3", "E. Africa Standard Time", "+03:00"},
	{"Etc/GMT-4", "Arabian Standard Time", "+04:00"},
	{"Etc/GMT-5", "West Asia Standard Time", "+05:00"},
	{"Etc/GMT-6", "Central Asia Standard Time", "+06:00"},
	{"Etc/GMT-7", "SE Asia Standard Time", "+07:00"},
	{"Etc/GMT-8", "Singapore Standard Time", "+08:00"},
	{"Etc/GMT-9", "Tokyo Standard Time", "+09:00"},
	{"Etc/GMT0", "UTC", "+00:00"},
	{"Etc/Greenwich", "UTC", "+00:00"},
	{"Etc/UCT", "UTC", "+00:00"},
	{"Etc/Universal", "UTC", "+00:00"},
	{"Etc/UTC", "UTC", "+00:00"},
	{"Etc/Zulu", "UTC", "+00:00"},
	{"Europe/Amsterdam", "W. Europe Standard Time", "+01:00"},
	{"Europe/Andorra", "W. Europe Standard Time", "+01:00"},
	{"Europe/Astrakhan", "Astrakhan Standard Time", "+04:00"},
	{"Europe/Athens", "GTB Standard Time", "+02:00"},
	{"Europe/Belfast", "GMT Standard Time", "+00:00"},
	{"Europe/Belgrade", "Central Europe Standard Time", "+01:00"},
	{"Europe/Berlin", "W. Europe Standard Time", "+01:00"},
	{"Europe/Bratislava", "Central Europe Standard Time", "+01:00"},
	{"Europe/Brussels", "Romance Standard Time", "+01:00"},
	{"Europe/Bucharest", "GTB Standard Time", "+02:00"},
	{"Europe/Budapest", "Central Europe Standard Time", "+01:00"},
	{"Europe/Busingen", "W. Europe Standard Time", "+01:00"},
	{"Europe/Chisinau", "E. Europe Standard Time", "+02:00"},
	{"Europe/Copenhagen", "Romance Standard Time", "+01:00"},
	{"Europe/Dublin", "GMT Standard Time", "+00:00"},
	{"Europe/Gibraltar", "W. Europe Standard Time", "+01:00"},
	{"Europe/Guernsey", "GMT Standard Time", "+00:00"},
	{"Europe/Helsinki", "FLE Standard Time", "+02:00"},
	{"Europe/Isle_of_Man", "GMT Standard Time", "+00:00"},
	{"Europe/Istanbul", "Turkey Standard Time", "+03:00"},
	{"Europe/Jersey", "GMT Standard Time", "+00:00"},
	{"Europe/Kaliningrad", "Kaliningrad Standard Time", "+02:00"},
	{"Europe/Kiev", "FLE Standard Time", "+02:00"},
	{"Europe/Kirov", "Russian Standard Time", "+03:00"},
	{"Europe/Lisbon", "GMT Standard Time", "+00:00"},
	{"Europe/Ljubljana", "Central Europe Standard Time", "+01:00"},
	{"Europe/London", "GMT Standard Time", "+00:00"},
	{"Europe/Luxembourg", "W. Europe Standard Time", "+01:00"},
	{"Europe/Madrid", "Romance Standard Time", "+01:00"},
	{"Europe/Malta", "W. Europe Standard Time", "+01:00"},
	{"Europe/Mariehamn", "FLE Standard Time", "+02:00"},
	{"Europe/Minsk", "Belarus Standard Time", "+03:00"},
	{"Europe/Monaco", "W. Europe Standard Time", "+01:00"},
	{"Europe/Moscow", "Russian Standard Time", "+03:00"},
	{"Europe/Nicosia", "GTB Standard Time", "+02:00"},
	{"Europe/Oslo", "W. Europe Standard Time", "+01:00"},
	{"Europe/Paris", "Romance Standard Time", "+01:00"},
	{"Europe/Podgorica", "Central Europe Standard Time", "+01:00"},
	{"Europe/Prague", "Central Europe Standard Time", "+01:00"},
	{"Europe/Riga", "FLE Standard Time", "+02:00"},
	{"Europe/Rome", "W. Europe Standard Time", "+01:00"},
	{"Europe/Samara", "Russia Time Zone 3", "+04:00"},
	{"Europe/San_Marino", "W. Europe Standard Time", "+01:00"},
	{"Europe/Sarajevo", "Central European Standard Time", "+01:00"},
	{"Europe/Simferopol", "Russian Standard Time", "+03:00"},
	{"Europe/Skopje", "Central European Standard Time", "+01:00"},
	{"Europe/Sofia", "FLE Standard Time", "+02:00"},
	{"Europe/Stockholm", "W. Europe Standard Time", "+01:00"},
	{"Europe/Tallinn", "FLE Standard Time", "+02:00"},
	{"Europe/Tirane", "Central Europe Standard Time", "+01:00"},
	{"Europe/Tiraspol", "E. Europe Standard Time", "+02:00"},
	{"Europe/Ulyanovsk", "Astrakhan Standard Time", "+04:00"},
	{"Europe/Uzhgorod", "FLE Standard Time", "+02:00"},
	{"Europe/Vaduz", "W. Europe Standard Time", "+01:00"},
	{"Europe/Vatican", "W. Europe Standard Time", "+01:00"},
	{"Europe/Vienna", "W. Europe Standard Time", "+01:00"},
	{"Europe/Vilnius", "FLE Standard Time", "+02:00"},
	{"Europe/Volgograd", "Russian Standard Time", "+03:00"},
	{"Europe/Warsaw", "Central European Standard Time", "+01:00"},
	{"Europe/Zagreb", "Central European Standard Time", "+01:00"},
	{"Europe/Zaporozhye", "FLE Standard Time", "+02:00"},
	{"Europe/Zurich", "W. Europe Standard Time", "+01:00"},
	{"GB", "GMT Standard Time", "+00:00"},
	{"GB-Eire", "GMT Standard Time", "+00:00"},
	{"GMT", "UTC", "+00:00"},
	{"GMT+0", "UTC", "+00:00"},
	{"GMT-0", "UTC", "+00:00"},
	{"GMT0", "UTC", "+00:00"},
	{"Greenwich", "UTC", "+00:00"},
	{"Hongkong", "China Standard Time", "+08:00"},
	{"HST", "Hawaiian Standard Time", "-10:00"},
	{"Iceland", "Greenwich Standard Time", "+00:00"},
	{"Indian/Antananarivo", "E. Africa Standard Time", "+03:00"},
	{"Indian/Chagos", "Central Asia Standard Time", "+06:00"},
	{"Indian/Christmas", "SE Asia Standard Time", "+07:00"},
	{"Indian/Cocos", "Myanmar Standard Time", "+06:30"},
	{"Indian/Comoro", "E. Africa Standard Time", "+03:00"},
	{"Indian/Kerguelen", "West Asia Standard Time", "+05:00"},
	{"Indian/Mahe", "Mauritius Standard Time", "+04:00"},
	{"Indian/Maldives", "West Asia Standard Time", "+05:00"},
	{"Indian/Mauritius", "Mauritius Standard Time", "+04:00"},
	{"Indian/Mayotte", "E. Africa Standard Time", "+03:00"},
	{"Indian/Reunion", "Mauritius Standard Time", "+04:00"},
	{"Iran", "Iran Standard Time", "+03:30"},
	{"Israel", "Israel Standard Time", "+02:00"},
	{"Jamaica", "SA Pacific Standard Time", "-05:00"},
	{"Japan", "Tokyo Standard Time", "+09:00"},
	{"Kwajalein", "UTC+12", "+12:00"},
	{"Libya", "Libya Standard Time", "+02:00"},
	{"Mexico/BajaNorte", "Pacific Standard Time (Mexico)", "-08:00"},
	{"Mexico/BajaSur", "Mountain Standard Time (Mexico)", "-07:00"},
	{"Mexico/General", "Central Standard Time (Mexico)", "-06:00"},
	{"MST", "US Mountain Standard Time", "-07:00"},
	{"MST7MDT", "Mountain Standard Time", "-07:00"},
	{"Navajo", "Mountain Standard Time", "-07:00"},
	{"NZ", "New Zealand Standard Time", "+12:00"},
	{"NZ-CHAT", "Chatham Islands Standard Time", "+12:45"},
	{"Pacific/Apia", "Samoa Standard Time", "+13:00"},
	{"Pacific/Auckland", "New Zealand Standard Time", "+12:00"},
	{"Pacific/Bougainville", "Bougainville Standard Time", "+11:00"},
	{"Pacific/Chatham", "Chatham Islands Standard Time", "+12:45"},
	{"Pacific/Chuuk", "West Pacific Standard Time", "+10:00"},
	{"Pacific/Easter", "Easter Island Standard Time", "-06:00"},
	{"Pacific/Efate", "Central Pacific Standard Time", "+11:00"},
	{"Pacific/Enderbury", "Tonga Standard Time", "+13:00"},
	{"Pacific/Fakaofo", "Tonga Standard Time", "+13:00"},
	{"Pacific/Fiji", "Fiji Standard Time", "+12:00"},
	{"Pacific/Funafuti", "UTC+12", "+12:00"},
	{"Pacific/Galapagos", "Central America Standard Time", "-06:00"},
	{"Pacific/Gambier", "UTC-09", "-09:00"},
	{"Pacific/Guadalcanal", "Central Pacific Standard Time", "+11:00"},
	{"Pacific/Guam", "West Pacific Standard Time", "+10:00"},
	{"Pacific/Honolulu", "Hawaiian Standard Time", "-10:00"},
	{"Pacific/Johnston", "Hawaiian Standard Time", "-10:00"},
	{"Pacific/Kiritimati", "Line Islands Standard Time", "+14:00"},
	{"Pacific/Kosrae", "Central Pacific Standard Time", "+11:00"},
	{"Pacific/Kwajalein", "UTC+12", "+12:00"},
	{"Pacific/Majuro", "UTC+12", "+12:00"},
	{"Pacific/Marquesas", "Marquesas Standard Time", "-09:30"},
	{"Pacific/Midway", "UTC-11", "-11:00"},
	{"Pacific/Nauru", "UTC+12", "+12:00"},
	{"Pacific/Niue", "UTC-11", "-11:00"},
	{"Pacific/Norfolk", "Norfolk Standard Time", "+11:00"},
	{"Pacific/Noumea", "Central Pacific Standard Time", "+11:00"},
	{"Pacific/Pago_Pago", "UTC-11", "-11:00"},
	{"Pacific/Palau", "Tokyo Standard Time", "+09:00"},
	{"Pacific/Pitcairn", "UTC-08", "-08:00"},
	{"Pacific/Pohnpei", "Central Pacific Standard Time", "+11:00"},
	{"Pacific/Ponape", "Central Pacific Standard Time", "+11:00"},
	{"Pacific/Port_Moresby", "West Pacific Standard Time", "+10:00"},
	{"Pacific/Rarotonga", "Hawaiian Standard Time", "-10:00"},
	{"Pacific/Saipan", "West Pacific Standard Time", "+10:00"},
	{"Pacific/Samoa", "UTC-11", "-11:00"},
	{"Pacific/Tahiti", "Hawaiian Standard Time", "-10:00"},
	{"Pacific/Tarawa", "UTC+12", "+12:00"},
	{"Pacific/Tongatapu", "Tonga Standard Time", "+13:00"},
	{"Pacific/Truk", "West Pacific Standard Time", "+10:00"},
	{"Pacific/Wake", "UTC+12", "+12:00"},
	{"Pacific/Wallis", "UTC+12", "+12:00"},
	{"Pacific/Yap", "West Pacific Standard Time", "+10:00"},
	{"Poland", "Central European Standard Time", "+01:00"},
	{"Portugal", "GMT Standard Time", "+00:00"},
	{"PRC", "China Standard Time", "+08:00"},
	{"PST8PDT", "Pacific Standard Time", "-08:00"},
	{"ROC", "Taipei Standard Time", "+08:00"},
	{"ROK", "Korea Standard Time", "+09:00"},
	{"Singapore", "Singapore Standard Time", "+08:00"},
	{"Turkey", "Turkey Standard Time", "+03:00"},
	{"UCT", "UTC", "+00:00"},
	{"Universal", "UTC", "+00:00"},
	{"US/Alaska", "Alaskan Standard Time", "-09:00"},
	{"US/Aleutian", "Aleutian Standard Time", "-10:00"},
	{"US/Arizona", "US Mountain Standard Time", "-07:00"},
	{"US/Central", "Central Standard Time", "-06:00"},
	{"US/East-Indiana", "US Eastern Standard Time", "-05:00"},
	{"US/Eastern", "Eastern Standard Time", "-05:00"},
	{"US/Hawaii", "Hawaiian Standard Time", "-10:00"},
	{"US/Indiana-Starke", "Central Standard Time", "-06:00"},
	{"US/Michigan", "Eastern Standard Time", "-05:00"},
	{"US/Mountain", "Mountain Standard Time", "-07:00"},
	{"US/Pacific", "Pacific Standard Time", "-08:00"},
	{"US/Pacific-New", "Pacific Standard Time", "-08:00"},
	{"US/Samoa", "UTC-11", "-11:00"},
	{"UTC", "UTC", "+00:00"},
	{"W-SU", "Russian Standard Time", "+03:00"},
	{"Zulu", "UTC", "+00:00"},
}
